# 1. Numpy 기초 연습문제

아래 문제들은 Numpy 패키지의 아주 기본적인 내용을 연습할 수 있는 문제입니다.

1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하고 내용을 출력하시오. <br>
이 때 생성된 ndarray의 이름은 a가 되도록 한다.<br>

In [1]:
import numpy as np
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용해 아래와 같은 값을 갖도록 초기화하고 내용을 출력하시오.
```
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])
```

In [12]:
a = np.arange(1, 13)
a = a.reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하여 출력하시오.

In [13]:
print(a[1][2])

7


4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하고 출력하시오. <br>
아래 결과에서 차원이 유지된 것에 주의하여 인덱싱을 하시오.

`array([[5., 6., 7., 8.]])`

In [16]:
print(a[1:2])

[[5 6 7 8]]


5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하고 결과를 출력하시오.

```
array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])
```

In [18]:
print(a[:3, 1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]


6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하고 결과를 출력하시오.

```array([1., 2., 3., 4., 5., 6.])```

In [20]:
print(a[a<=6])

[1 2 3 4 5 6]


7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. <br>
이 때 생성된 ndarray의 이름은 b가 되도록 한다. <br>
그리고 아래와 같이 랜덤 시드 설정을 7로 하고 실행하시오.

`np.random.seed(7)`

In [22]:
np.random.seed(7)
b = np.random.rand(3, 4)
print(b)

[[0.07630829 0.77991879 0.43840923 0.72346518]
 [0.97798951 0.53849587 0.50112046 0.07205113]
 [0.26843898 0.4998825  0.67923    0.80373904]]


8. a와 b의 요소곱을 하여 c에 저장하고 결과를 출력하시오

In [23]:
c = np.multiply(a, b)
print(c)

[[0.07630829 1.55983758 1.31522769 2.89386071]
 [4.88994756 3.23097522 3.50784325 0.57640907]
 [2.41595082 4.99882501 7.47152996 9.64486843]]


9. b의 전치행렬을 구하여 d에 저장하고 결과를 출력하시오.

In [31]:
d = b.T
print(d)

[[0.07630829 0.97798951 0.26843898]
 [0.77991879 0.53849587 0.4998825 ]
 [0.43840923 0.50112046 0.67923   ]
 [0.72346518 0.07205113 0.80373904]]


10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [32]:
print(a.shape, d.shape)

(3, 4) (4, 3)


11. a와 d의 행렬곱을 계산하여 e에 저장하고 결과를 출력하시오.

In [34]:
e = np.dot(a, d)
print(e)

[[ 5.84523428  3.84654718  6.52085011]
 [13.91764024 12.20517509 15.52601217]
 [21.99004621 20.56380301 24.53117422]]


12. e에 대하여 각 열의 합을 계산하여 출력하시오.

In [36]:
e = np.sum(e, axis=0)
print(e)

[41.75292073 36.61552528 46.5780365 ]


In [37]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [38]:
!jupyter nbconvert --to html "/content/drive/MyDrive/Colab Notebooks/01_NumpyQ.ipynb의 사본"

[NbConvertApp] Converting notebook /content/drive/MyDrive/Colab Notebooks/01_NumpyQ.ipynb의 사본 to html
[NbConvertApp] Writing 299511 bytes to /content/drive/MyDrive/Colab Notebooks/01_NumpyQ.html
